name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Debugging List contents of front-end directory
      run: |
        ls -la front-end

    - name: Change directory to front-end   
      run: |
        cd front-end

    - name: Debugging List contents of front-end directory after changing directory
      run: |
        ls -la

    - name: Build
      run: |
        npm install
        npx webpack
